'use strict';(function(){function Q(a){a-=179;return!Number.isInteger(a)||0>a||a>=Z.length?0:Z[a]}function M(a){return ea[a]||0}function X(a,b,h,e,l,k,g){let [f,m]=a<h?[a,h]:[h,a],[r,p]=b<e?[b,e]:[e,b];a=g?32:0;g=g?16:0;if(r===p)if(f===m)k(f,r,M(15));else{k(f,r,M(Q(l(f,r))&-33|8|a));for(g=f+1;g<m;g++)k(g,r,M(Q(l(g,r))&-33|12|a));k(m,r,M(Q(l(m,r))&-33|4|a))}else if(f===m){k(f,r,M(Q(l(f,r))&-17|2|g));for(a=r+1;a<p;a++)k(f,a,M(Q(l(f,a))&-17|3|g));k(f,p,M(Q(l(f,p))&-17|1|g))}else{k(f,r,M(Q(l(f,r))&-49|
10|a|g));for(b=f+1;b<m;b++)k(b,r,M(Q(l(b,r))&-33|12|a));k(m,r,M(Q(l(m,r))&-49|6|a|g));for(b=r+1;b<p;b++)k(f,b,M(Q(l(f,b))&-17|3|g)),k(m,b,M(Q(l(m,b))&-17|3|g));k(f,p,M(Q(l(f,p))&-49|9|a|g));for(b=f+1;b<m;b++)k(b,p,M(Q(l(b,p))&-33|12|a));k(m,p,M(Q(l(m,p))&-49|5|g|a))}}function*W(a,b,h,e){let l=Math.abs(h-a),k=Math.abs(e-b),g=a<h?1:-1,f=b<e?1:-1,m=l-k;for(;;){yield[a,b];if(a===h&&b===e)break;let r=2*m;r>-k&&(m-=k,a+=g);r<l&&(m+=l,b+=f)}}function*aa(a,b,h,e){let l=Math.sign(h-a),k=Math.sign(e-b);if(0===
l)if(0===k)yield[a,b];else for(h=b;h!==e+k;h+=k)yield[a,h];else if(0===k)for(;a!==h+l;a+=l)yield[a,b];else for(;b!==e+k;b+=k)for(let g=a;g!==h+l;g+=l)yield[g,b]}function*ba(a,b,h,e){let l=Math.sign(h-a),k=Math.sign(e-b);if(0===l)if(0===k)yield[a,b];else for(h=b;h!==e+k;h+=k)yield[a,h];else if(0===k)for(e=a;e!==h+l;e+=l)yield[e,b];else{for(let g=a;g!==h+l;g+=l)yield[g,b];for(b+=k;b!==e;b+=k)yield[a,b],yield[h,b];for(;a!==h+l;a+=l)yield[a,e]}}function fa(){return new Promise((a,b)=>{let h=document.createElement("input");
h.type="file";h.onchange=e=>{var l;(null===(l=h.files)||void 0===l?0:l.length)?a(h.files[0]):a(null)};h.click()})}function L(a,b){let h=0;for(;a&b;){var e=Math.clz32(b);e=32-Math.clz32(~b<<e>>>e);e=b>>>e<<e;e&a&&(h|=e,a&=~e);b&=~e}return h}function ha(a,b,h,e,l,k,g){if(!(0>a||0>b||80<=a||25<=b)){var f=Math.floor(a%1*8),m=Math.floor(b%1*8);a=Math.floor(a);b=Math.floor(b);var {charCode:r,bgColor:p,fgColor:T}=h(a,b);if(p===T||32===r||255===r)r=0;var O=!!(l[r][m]&128>>>f),J=O?T:p,A=[],F=O?0:255,B=O?0:
65535,K=L(128>>>f,l[r][m]^F),I=L(32768>>>m,k[r][f]^B);a:if(0!==b){var U=K;for(let u=m-1;0<=u;u--)if(U=L(U,l[r][u]^F),0===U)break a;A.push({x:a,y:b-1,side:"bottom",mask:U})}a:if(24!==b){for(m+=1;8>m;m++)if(K=L(K,l[r][m]^F),0===K)break a;A.push({x:a,y:b+1,side:"top",mask:K})}a:if(0!==a){F=I;for(m=f-1;0<=m;m--)if(F=L(F,k[r][m]^B),0===F)break a;A.push({x:a-1,y:b,side:"right",mask:F})}a:if(79!==a){for(f+=1;8>f;f++)if(I=L(I,k[r][f]^B),0===I)break a;A.push({x:a+1,y:b,side:"left",mask:I})}O?e(a,b,r,g,p):
e(a,b,r,T,g);for(a=new Set([`${a},${b}`]);0<A.length;){let {x:u,y:w,side:V,mask:C}=A.pop(),{charCode:G,bgColor:P,fgColor:R}=h(u,w);if(P!==J&&R!==J||177===G||176===G&&P!==J||178===G&&R!==J)a.add(`${u},${w}`);else{if(R===P||32===G||255===G)G=0;b=P===J?255:0;O=P===J?65535:0;switch(V){case "top":for(B=I=f=0;16>B;B++){C=L(C,l[G][B]^b);if(0===C)break;C&128&&(f|=L(1<<B,k[G][0]^O));C&1&&(I|=L(1<<B,k[G][7]^O))}0<B&&(C&&24!==w&&!a.has(`${u},${w+1}`)&&A.push({x:u,y:w+1,side:"top",mask:C}),f&&0!==u&&!a.has(`${u-
1},${w}`)&&A.push({x:u-1,y:w,side:"right",mask:f}),I&&79!==u&&!a.has(`${u+1},${w}`)&&A.push({x:u+1,y:w,side:"left",mask:I}),P===J?e(u,w,G,R,g):e(u,w,G,g,P),a.add(`${u},${w}`));break;case "bottom":I=f=0;for(B=15;0<=B;B--){C=L(C,l[G][B]^b);if(0===C)break;C&128&&(f|=L(1<<B,k[G][0]^O));C&1&&(I|=L(1<<B,k[G][7]^O))}15>B&&(C&&0!==w&&!a.has(`${u},${w-1}`)&&A.push({x:u,y:w-1,side:"bottom",mask:C}),f&&0!==u&&!a.has(`${u-1},${w}`)&&A.push({x:u-1,y:w,side:"right",mask:f}),I&&79!==u&&!a.has(`${u+1},${w}`)&&A.push({x:u+
1,y:w,side:"left",mask:I}),P===J?e(u,w,G,R,g):e(u,w,G,g,P),a.add(`${u},${w}`));break;case "left":for(B=I=f=0;8>B;B++){C=L(C,k[G][B]^O);if(0===C)break;C&32768&&(I|=L(128>>B,l[G][15]^b));C&1&&(f|=L(128>>B,l[G][0]^b))}0<B&&(C&&79!==u&&!a.has(`${u+1},${w}`)&&A.push({x:u+1,y:w,side:"left",mask:C}),f&&0!==w&&!a.has(`${u},${w-1}`)&&A.push({x:u,y:w-1,side:"bottom",mask:f}),I&&24!==w&&!a.has(`${u},${w+1}`)&&A.push({x:u,y:w+1,side:"top",mask:I}),P===J?e(u,w,G,R,g):e(u,w,G,g,P),a.add(`${u},${w}`));break;case "right":I=
f=0;for(B=7;0<=B;B--){C=L(C,k[G][B]^O);if(0===C)break;C&32768&&(I|=L(128>>B,l[G][15]^b));C&1&&(f|=L(128>>B,l[G][0]^b))}7>B&&(C&&0!==u&&!a.has(`${u-1},${w}`)&&A.push({x:u-1,y:w,side:"right",mask:C}),f&&0!==w&&!a.has(`${u},${w-1}`)&&A.push({x:u,y:w-1,side:"bottom",mask:f}),I&&24!==w&&!a.has(`${u},${w+1}`)&&A.push({x:u,y:w+1,side:"top",mask:I}),P===J?e(u,w,G,R,g):e(u,w,G,g,P),a.add(`${u},${w}`))}}}}}let ca=1===(new Uint8Array((new Uint16Array([1])).buffer))[0];var N;(function(a){a[a.Tile=255]="Tile";
a[a.ForegroundColor=3840]="ForegroundColor";a[a.BackgroundColor=61440]="BackgroundColor";a[a.All=65535]="All"})(N||(N={}));var Y;(function(a){a[a.Black=0]="Black";a[a.DarkBlue=1]="DarkBlue";a[a.DarkGreen=2]="DarkGreen";a[a.DarkCyan=3]="DarkCyan";a[a.DarkRed=4]="DarkRed";a[a.DarkMagenta=5]="DarkMagenta";a[a.Brown=6]="Brown";a[a.LightGrey=7]="LightGrey";a[a.DarkGrey=8]="DarkGrey";a[a.Blue=9]="Blue";a[a.Green=10]="Green";a[a.Cyan=11]="Cyan";a[a.Red=12]="Red";a[a.Magenta=13]="Magenta";a[a.Yellow=14]=
"Yellow";a[a.White=15]="White"})(Y||(Y={}));let da="#000 #008 #080 #088 #800 #808 #880 #ccc #888 #00f #0f0 #0ff #f00 #f0f #ff0 #fff".split(" ");class ia{constructor(a){this.drawChar=a;this.buffer=new Uint16Array(2E3);this.buffer.fill(1792);this.canvas=document.createElement("canvas");this.canvas.width=640;this.canvas.height=400;this.ctx=this.canvas.getContext("2d");if(!this.ctx)throw Error("unable to get canvas context");}getBrush(a,b,h,e){if(!Number.isInteger(a)||!Number.isInteger(b))throw new TypeError("x and y must be integers");
if(!Number.isInteger(h)||!Number.isInteger(b))throw new TypeError("width and height must be integers");if(0>a||0>b||0>h||0>e||80<a+h||25<b+e)throw new RangeError("edges exceed screen");let l=new Uint16Array(h*e);for(let k=0;k<e;k++)l.set(this.buffer.subarray(80*(b+k)+a,80*(b+k)+a+h),k*h);return{data:l,width:h,height:e}}putBrush(a,b,h){let e,l,k=a.data;if(0>b){e=-b;if(e>=a.width)return;b=0}else e=0;l=Math.min(80-b,b+a.width);if(0>h){k=k.subarray(h*a.width);if(0===k.length)return;h=0}for(let g=0;g<
a.height;g++)if(!(0>h+g)){if(25<=h+g)break;this.buffer.set(k.subarray((h+g)*a.width+e,(h+g)*a.width+l),80*h+b);for(let f=e;f<l;f++)this.updateCanvas(h+g,b+f)}}updateCanvas(a,b){let h=this.buffer[80*b+a];this.drawChar(this.ctx,a,b,h&255,h>>8&15,h>>12&15)}getCharInfo(a,b){a=this.buffer[80*b+a];return{charCode:a&255,fgColor:a>>8&15,bgColor:a>>12&15}}getChar(a,b){return this.buffer[80*b+a]&255}putChar(a,b,h,e,l){this.buffer[80*b+a]=h|e<<8|l<<12;this.updateCanvas(a,b)}setChar(a,b,h,e,l,k=N.All){this.buffer[80*
b+a]=this.buffer[80*b+a]&~k|(h|e<<8|l<<12)&k;this.updateCanvas(a,b)}fill(a,b,h,e=N.All){a=(a|b<<8|h<<12)&e;for(b=0;b<this.buffer.length;b++)this.buffer[b]=this.buffer[b]&~e|a,this.updateCanvas(b%80,Math.floor(b/80))}putVHalf(a,b,h){var e=this.buffer[80*(b>>1)+a];let l=e>>>8&15,k=e>>>12&15,g=b&1;switch(e&255){case 219:case 8:case 10:e=l;break;default:e=k;break;case 220:e=1===g?k:l;break;case 223:e=1===g?l:k}e===h?this.putChar(a,b>>1,219,h,k):0===g?this.putChar(a,b>>1,223,h,e):this.putChar(a,b>>1,220,
h,e)}putHHalf(a,b,h){var e=this.buffer[80*b+(a>>1)];let l=e>>>8&15,k=e>>>12&15,g=a&1;switch(e&255){case 219:case 8:case 10:e=l;break;default:e=k;break;case 222:e=1===g?k:l;break;case 221:e=1===g?l:k}e===h?this.putChar(a>>1,b,219,h,k):0===g?this.putChar(a>>1,b,221,h,e):this.putChar(a>>1,b,222,h,e)}saveBlob(){if(ca)return new Blob([this.buffer]);let a=new Uint16Array(this.buffer);for(let b=0;b<a.length;b++)a[b]=a[b]>>8|a[b]<<8;return new Blob([a],{type:"application/octet-stream"})}async loadBlob(a){a=
await a.arrayBuffer();if(a.byteLength!==this.buffer.byteLength)throw Error("invalid file");a=new Uint16Array(a);if(!ca)for(var b=0;b<a.length;b++)a[b]=a[b]>>8|a[b]<<8;this.buffer.set(a);for(a=0;25>a;a++)for(b=0;80>b;b++)this.updateCanvas(b,a)}}let ea=new Uint8Array([0,193,194,179,180,217,191,180,195,192,218,195,196,193,194,197,0,208,210,186,180,189,183,182,195,211,214,199,196,208,210,215,0,180,203,179,181,190,184,181,198,212,213,198,205,207,209,216,0,208,210,186,181,188,187,185,198,200,201,204,205,
202,203,206]),Z=new Uint8Array([3,7,39,23,22,38,55,19,54,53,21,37,6,9,13,14,11,12,15,43,27,57,58,61,62,59,44,63,45,29,46,30,25,41,42,26,31,47,5,10]),ja=fetch("./chardata.png"),ka=a=>{var b=document.createElement("canvas");b.width=a.width;b.height=a.height;b=b.getContext("2d");if(!b)throw Error("unable to create 2D canvas");b.drawImage(a,0,0);var h=a.width/9;a=new Uint8Array(4096);for(let e=0;256>e;e++){const {data:l}=b.getImageData(e%h*9,16*Math.floor(e/h),8,16);for(let k=0;16>k;k++)a[16*e+k]=l[32*
k+3]?128:0,a[16*e+k]|=l[4*(8*k+1)+3]?64:0,a[16*e+k]|=l[4*(8*k+2)+3]?32:0,a[16*e+k]|=l[4*(8*k+3)+3]?16:0,a[16*e+k]|=l[4*(8*k+4)+3]?8:0,a[16*e+k]|=l[4*(8*k+5)+3]?4:0,a[16*e+k]|=l[4*(8*k+5)+3]?2:0,a[16*e+k]|=l[4*(8*k+7)+3]?1:0}b=Array(256);for(h=0;256>h;h++)b[h]=a.subarray(16*h,16*(h+1));return b},la=a=>{const b=new Uint16Array(2048);for(var h=0;256>h;h++)for(let e=0;8>e;e++)for(let l=0;16>l;l++)b[8*h+e]|=(a[h][l]>>>7-e&1)<<l;a=Array(256);for(h=0;256>h;h++)a[h]=b.subarray(8*h,8*(h+1));return a};Y=[0,
9786,9787,9829,9830,9827,9824,8226,9688,9675,9689,9794,9792,9834,9835,9788,9658,9668,8597,8252,182,167,9644,8616,8593,8595,8594,8592,8735,8596,9650,9660,...Array.from({length:223},(a,b)=>32+b),8962,199,252,233,226,228,224,229,231,234,235,232,239,238,236,196,197,201,230,198,244,246,242,251,249,255,214,220,162,163,165,8359,402,225,237,243,250,241,209,170,186,191,8976,172,189,188,161,171,187,9617,9618,9619,9474,9508,9569,9570,9558,9557,9571,9553,9559,9565,9564,9563,9488,9492,9524,9516,9500,9472,9532,
9566,9567,9562,9556,9577,9574,9568,9552,9580,9575,9576,9572,9573,9561,9560,9554,9555,9579,9578,9496,9484,9608,9604,9612,9616,9600,945,223,915,960,931,963,181,964,934,920,937,948,8734,966,949,8745,8801,177,8805,8804,8992,8993,247,8776,176,8729,183,8730,8319,178,9632,160];let ma=new Map(Y.map((a,b)=>[String.fromCodePoint(a),b]));window.addEventListener("DOMContentLoaded",async function(){var a=await (await ja).blob();let b=await createImageBitmap(a),h=b.width/9,e=(d,c,t,x,v,y)=>{d.save();d.globalCompositeOperation=
"source-over";d.fillStyle=da[y];d.fillRect(8*c,16*t,8,16);d.globalCompositeOperation="destination-out";d.drawImage(b,x%h*9,16*Math.floor(x/h),8,16,8*c,16*t,8,16);d.globalCompositeOperation="destination-over";d.fillStyle=da[v];d.fillRect(8*c,16*t,8,16);d.restore()},l=ka(b),k=la(l),g=new ia(e),f=document.getElementById("editor"),m=f.getContext("2d");if(!m)throw Error("unable to create canvas context");let r=N.All;document.getElementById("tile").onchange=d=>{r=d.target.checked?r|N.Tile:r&~N.Tile};document.getElementById("fgcolor").onchange=
d=>{r=d.target.checked?r|N.ForegroundColor:r&~N.ForegroundColor};document.getElementById("bgcolor").onchange=d=>{r=d.target.checked?r|N.BackgroundColor:r&~N.BackgroundColor};let p=[7,0,0],T=document.querySelector(".palette"),O=(d,c)=>{const t=c?"background-selected":"foreground-selected";var x=T.querySelectorAll(`.${t}`);for(let v=0;v<x.length;v++)x[v].classList.remove(t);(x=T.querySelector(`.color-cell[data-value='${d}']`))&&x.classList.add(t);p[c?2:0]=d};T.onpointerdown=d=>{if("mouse"===d.pointerType&&
(0===d.button||2===d.button)){var c=0===d.button?"foreground-selected":"background-selected";for(let t=d.target;t&&!t.classList.contains("palette");t=t.parentElement)if("value"in t.dataset){let x=T.querySelectorAll(`.${c}`);for(let v=0;v<x.length;v++)x[v].classList.remove(c);t.classList.add(c);p[d.button]=+t.dataset.value;d.preventDefault();d.stopPropagation();break}}};T.oncontextmenu=d=>{d.preventDefault()};let J=[219,0,0],A=0,F=0,B=document.querySelector(".cursor"),K=(d,c)=>{B.style.left=`${8*d}px`;
B.style.top=`${16*c}px`;A=d;F=c},I=document.querySelector("#editor-block"),U={freehand:()=>{f.onpointerdown=d=>{if("mouse"===d.pointerType){const {button:y,pointerId:D}=d;if(0===y||2===y){function H(q){q.pointerId===D&&q.button===y&&(f.removeEventListener("pointermove",n),f.removeEventListener("pointerup",H))}function n(q){if(q.pointerId===D){var z=Math.floor(80*(q.clientX-c.x)/c.width);q=Math.floor(25*(q.clientY-c.y)/c.height);for(const [E,S]of W(x,v,z,q))g.setChar(E,S,J[y],p[0],p[2],r);m.drawImage(g.canvas,
0,0);x=z;v=q}}d.preventDefault();f.setPointerCapture(D);var c=f.getBoundingClientRect(),t=Math.floor(80*(d.clientX-c.x)/c.width);d=Math.floor(25*(d.clientY-c.y)/c.height);g.setChar(t,d,J[y],p[0],p[2],r);m.drawImage(g.canvas,0,0);var x=t,v=d;f.addEventListener("pointermove",n);f.addEventListener("pointerup",H)}}}},vbFreehand:()=>{f.onpointerdown=d=>{if("mouse"===d.pointerType){const {button:y,pointerId:D}=d;if(0===y||2===y){function H(q){q.pointerId===D&&q.button===y&&(f.removeEventListener("pointermove",
n),f.removeEventListener("pointerup",H))}function n(q){if(q.pointerId===D){var z=Math.floor(80*(q.clientX-c.x)/c.width);q=Math.floor(50*(q.clientY-c.y)/c.height);for(const [E,S]of W(x,v,z,q))g.putVHalf(E,S,p[y]);m.drawImage(g.canvas,0,0);x=z;v=q}}d.preventDefault();f.setPointerCapture(D);var c=f.getBoundingClientRect(),t=Math.floor(80*(d.clientX-c.x)/c.width);d=Math.floor(50*(d.clientY-c.y)/c.height);g.putVHalf(t,d,p[y]);m.drawImage(g.canvas,0,0);var x=t,v=d;f.addEventListener("pointermove",n);f.addEventListener("pointerup",
H)}}}},hbFreehand:()=>{f.onpointerdown=d=>{if("mouse"===d.pointerType){const {button:y,pointerId:D}=d;if(0===y||2===y){function H(q){q.pointerId===D&&q.button===y&&(f.removeEventListener("pointermove",n),f.removeEventListener("pointerup",H))}function n(q){if(q.pointerId===D){var z=Math.floor(160*(q.clientX-c.x)/c.width);q=Math.floor(25*(q.clientY-c.y)/c.height);for(const [E,S]of W(x,v,z,q))g.putHHalf(E,S,p[y]);m.drawImage(g.canvas,0,0);x=z;v=q}}d.preventDefault();f.setPointerCapture(D);var c=f.getBoundingClientRect(),
t=Math.floor(160*(d.clientX-c.x)/c.width);d=Math.floor(25*(d.clientY-c.y)/c.height);g.putHHalf(t,d,p[y]);m.drawImage(g.canvas,0,0);var x=t,v=d;f.addEventListener("pointermove",n);f.addEventListener("pointerup",H)}}}},lines:()=>{f.onpointerdown=d=>{if("mouse"===d.pointerType){const {button:v,pointerId:y}=d;if(0===v||2===v){function D(n){if(n.pointerId===y&&n.button===v){var q=Math.floor(80*(n.clientX-c.x)/c.width);n=Math.floor(25*(n.clientY-c.y)/c.height);for(const [z,E]of W(t,x,q,n))g.setChar(z,E,
J[v],p[0],p[2],r);m.globalCompositeOperation="copy";m.drawImage(g.canvas,0,0);f.removeEventListener("pointermove",H);f.removeEventListener("pointerup",D)}}function H(n){if(n.pointerId===y){var q=Math.floor(80*(n.clientX-c.x)/c.width);n=Math.floor(25*(n.clientY-c.y)/c.height);m.globalCompositeOperation="copy";m.drawImage(g.canvas,0,0);for(const [z,E]of W(t,x,q,n))e(m,z,E,J[v],p[0],p[2])}}d.preventDefault();f.setPointerCapture(y);var c=f.getBoundingClientRect(),t=Math.floor(80*(d.clientX-c.x)/c.width),
x=Math.floor(25*(d.clientY-c.y)/c.height);e(m,t,x,J[v],p[0],p[2]);f.addEventListener("pointermove",H);f.addEventListener("pointerup",D)}}}},filledBox:()=>{f.onpointerdown=d=>{if("mouse"===d.pointerType){const {button:v,pointerId:y}=d;if(0===v||2===v){function D(n){if(n.pointerId===y&&n.button===v){var q=Math.floor(80*(n.clientX-c.x)/c.width);n=Math.floor(25*(n.clientY-c.y)/c.height);for(const [z,E]of aa(t,x,q,n))g.setChar(z,E,J[v],p[0],p[2],r);m.globalCompositeOperation="copy";m.drawImage(g.canvas,
0,0);f.removeEventListener("pointermove",H);f.removeEventListener("pointerup",D)}}function H(n){if(n.pointerId===y){var q=Math.floor(80*(n.clientX-c.x)/c.width);n=Math.floor(25*(n.clientY-c.y)/c.height);m.globalCompositeOperation="copy";m.drawImage(g.canvas,0,0);for(const [z,E]of aa(t,x,q,n))e(m,z,E,J[v],p[0],p[2])}}d.preventDefault();f.setPointerCapture(y);var c=f.getBoundingClientRect(),t=Math.floor(80*(d.clientX-c.x)/c.width),x=Math.floor(25*(d.clientY-c.y)/c.height);e(m,t,x,J[v],p[0],p[2]);f.addEventListener("pointermove",
H);f.addEventListener("pointerup",D)}}}},emptyBox:()=>{f.onpointerdown=d=>{if("mouse"===d.pointerType){const {button:v,pointerId:y}=d;if(0===v||2===v){function D(n){if(n.pointerId===y&&n.button===v){var q=Math.floor(80*(n.clientX-c.x)/c.width);n=Math.floor(25*(n.clientY-c.y)/c.height);for(const [z,E]of ba(t,x,q,n))g.setChar(z,E,J[v],p[0],p[2],r);m.globalCompositeOperation="copy";m.drawImage(g.canvas,0,0);f.removeEventListener("pointermove",H);f.removeEventListener("pointerup",D)}}function H(n){if(n.pointerId===
y){var q=Math.floor(80*(n.clientX-c.x)/c.width);n=Math.floor(25*(n.clientY-c.y)/c.height);m.globalCompositeOperation="copy";m.drawImage(g.canvas,0,0);for(const [z,E]of ba(t,x,q,n))e(m,z,E,J[v],p[0],p[2])}}d.preventDefault();f.setPointerCapture(y);var c=f.getBoundingClientRect(),t=Math.floor(80*(d.clientX-c.x)/c.width),x=Math.floor(25*(d.clientY-c.y)/c.height);e(m,t,x,J[v],p[0],p[2]);f.addEventListener("pointermove",H);f.addEventListener("pointerup",D)}}}},singleBorder:()=>{f.onpointerdown=d=>{if("mouse"===
d.pointerType){const {button:v,pointerId:y}=d;if(0===v||2===v){function D(n){n.pointerId===y&&n.button===v&&(X(t,x,Math.floor(80*(n.clientX-c.x)/c.width),Math.floor(25*(n.clientY-c.y)/c.height),(q,z)=>g.getChar(q,z),(q,z,E)=>g.putChar(q,z,E,p[0],p[2]),!1),m.globalCompositeOperation="copy",m.drawImage(g.canvas,0,0),f.removeEventListener("pointermove",H),f.removeEventListener("pointerup",D))}function H(n){if(n.pointerId===y){var q=Math.floor(80*(n.clientX-c.x)/c.width);n=Math.floor(25*(n.clientY-c.y)/
c.height);m.globalCompositeOperation="copy";m.drawImage(g.canvas,0,0);X(t,x,q,n,(z,E)=>g.getChar(z,E),(z,E,S)=>e(m,z,E,S,p[0],p[2]),!1)}}d.preventDefault();f.setPointerCapture(y);var c=f.getBoundingClientRect(),t=Math.floor(80*(d.clientX-c.x)/c.width),x=Math.floor(25*(d.clientY-c.y)/c.height);e(m,t,x,M(15),p[0],p[2]);f.addEventListener("pointermove",H);f.addEventListener("pointerup",D)}}}},doubleBorder:()=>{f.onpointerdown=d=>{if("mouse"===d.pointerType){const {button:v,pointerId:y}=d;if(0===v||2===
v){function D(n){n.pointerId===y&&n.button===v&&(X(t,x,Math.floor(80*(n.clientX-c.x)/c.width),Math.floor(25*(n.clientY-c.y)/c.height),(q,z)=>g.getChar(q,z),(q,z,E)=>g.putChar(q,z,E,p[0],p[2]),!0),m.globalCompositeOperation="copy",m.drawImage(g.canvas,0,0),f.removeEventListener("pointermove",H),f.removeEventListener("pointerup",D))}function H(n){if(n.pointerId===y){var q=Math.floor(80*(n.clientX-c.x)/c.width);n=Math.floor(25*(n.clientY-c.y)/c.height);m.globalCompositeOperation="copy";m.drawImage(g.canvas,
0,0);X(t,x,q,n,(z,E)=>g.getChar(z,E),(z,E,S)=>e(m,z,E,S,p[0],p[2]),!0)}}d.preventDefault();f.setPointerCapture(y);var c=f.getBoundingClientRect(),t=Math.floor(80*(d.clientX-c.x)/c.width),x=Math.floor(25*(d.clientY-c.y)/c.height);e(m,t,x,M(15),p[0],p[2]);f.addEventListener("pointermove",H);f.addEventListener("pointerup",D)}}}},colorFloodFill:()=>{f.onpointerdown=d=>{if("mouse"===d.pointerType){const {button:t}=d;if(0===t||2===t){d.preventDefault();var c=f.getBoundingClientRect();ha(80*(d.clientX-c.x)/
c.width,25*(d.clientY-c.y)/c.height,(x,v)=>g.getCharInfo(x,v),(x,v,y,D,H)=>g.putChar(x,v,y,D,H),l,k,p[t]);m.globalCompositeOperation="copy";m.drawImage(g.canvas,0,0)}}}},pick:()=>{f.onpointerdown=d=>{if("mouse"===d.pointerType){const {button:y,pointerId:D}=d;if(0===y||2===y){function H(q){q.pointerId===D&&q.button===y&&(f.removeEventListener("pointermove",n),f.removeEventListener("pointerup",H))}function n(q){if(q.pointerId===D&&q.button===y){var z=f.getBoundingClientRect(),{charCode:E,fgColor:S,
bgColor:na}=g.getCharInfo(Math.floor(80*(q.clientX-z.x)/z.width),Math.floor(25*(q.clientY-z.y)/z.height));r&N.Tile&&R(E,2===y);r&N.ForegroundColor&&O(S,!1);r&N.BackgroundColor&&O(na,!0)}}d.preventDefault();f.setPointerCapture(D);var c=f.getBoundingClientRect(),{charCode:t,fgColor:x,bgColor:v}=g.getCharInfo(Math.floor(80*(d.clientX-c.x)/c.width),Math.floor(25*(d.clientY-c.y)/c.height));r&N.Tile&&R(t,2===y);r&N.ForegroundColor&&O(x,!1);r&N.BackgroundColor&&O(v,!0);f.addEventListener("pointermove",n);
f.addEventListener("pointerup",H)}}}},text:()=>{function d(c){console.log(c.key);if("Tab"!==c.key){c.preventDefault();c.stopPropagation();switch(c.key){case "ArrowDown":K(A,Math.min(F+1,24));return;case "ArrowUp":K(A,Math.max(F-1,0));return;case "ArrowLeft":0===A?0!==F&&K(79,F-1):K(A-1,F);return;case "ArrowRight":79===A?24!==F&&K(0,F+1):K(A+1,F);return;case "Enter":K(0,Math.min(24,F+1));return;case "End":case "PageDown":K(A,24);return;case "Home":case "PageUp":K(A,0);return;case "Backspace":0===A?
0!==F&&K(79,F-1):K(A-1,F);g.setChar(A,F,0,p[0],p[2],r);m.globalCompositeOperation="copy";m.drawImage(g.canvas,0,0);return;case "Delete":g.setChar(A,F,0,p[0],p[2],r);m.globalCompositeOperation="copy";m.drawImage(g.canvas,0,0);return}c=ma.get(c.key);"number"===typeof c&&(g.setChar(A,F,c,p[0],p[2],r),m.globalCompositeOperation="copy",m.drawImage(g.canvas,0,0),79===A?24!==F&&K(0,F+1):K(A+1,F))}}I.focus();f.onpointerdown=c=>{if("mouse"===c.pointerType){var {button:t}=c;0===t&&(c.preventDefault(),t=f.getBoundingClientRect(),
K(Math.floor(80*(c.clientX-t.x)/t.width),Math.floor(25*(c.clientY-t.y)/t.height)),I.focus())}};I.addEventListener("keydown",d);return()=>{I.removeEventListener("keydown",d)}}},u;u=U.freehand();let w=document.getElementById("tool-selector"),V=w.value;document.body.classList.add("tool-"+V);w.onchange=d=>{u&&u();u=U[w.value]();document.body.classList.remove("tool-"+V);V=w.value;document.body.classList.add("tool-"+V)};f.oncontextmenu=d=>{d.preventDefault()};let C=document.getElementById("char-picker"),
G=document.querySelector(".left-pick"),P=document.querySelector(".right-pick"),R=(d,c)=>{const t=Math.floor(d/64),x=c?P:G;x.style.left=`${d%64*8}px`;x.style.top=`${16*t}px`;J[c?2:0]=d};a=C.getContext("2d");if(!a)throw Error("unable to create canvas context");for(let d=0;256>d;d++)e(a,d%64,Math.floor(d/64),d,7,0);C.onpointerdown=d=>{if("mouse"===d.pointerType&&(0===d.button||2===d.button)){var c=C.getBoundingClientRect();R(64*Math.floor(4*(d.clientY-c.y)/c.height)+Math.floor(64*(d.clientX-c.x)/c.width),
2===d.button)}};C.oncontextmenu=d=>{d.preventDefault()};document.getElementById("save-image").onclick=d=>{d=g.saveBlob();d=URL.createObjectURL(d);let c=document.createElement("a");c.download="dosimage.dat";c.href=d;c.click()};document.getElementById("load-image").onclick=async d=>{if(d=await fa()){try{await g.loadBlob(d)}catch(c){alert(c);return}m.drawImage(g.canvas,0,0)}};document.getElementById("clear-image").onclick=d=>{g.fill(J[2],p[0],p[2],r);m.drawImage(g.canvas,0,0)}},{once:!0})})()
