'use strict';(function(){function K(a){a-=179;return!Number.isInteger(a)||0>a||a>=S.length?0:S[a]}function H(a){return Y[a]||0}function R(a,c,g,e,l,k,h){let [f,p]=a<g?[a,g]:[g,a],[v,u]=c<e?[c,e]:[e,c];a=h?32:0;h=h?16:0;if(v===u)if(f===p)k(f,v,H(15));else{k(f,v,H(K(l(f,v))&-33|8|a));for(h=f+1;h<p;h++)k(h,v,H(K(l(h,v))&-33|12|a));k(p,v,H(K(l(p,v))&-33|4|a))}else if(f===p){k(f,v,H(K(l(f,v))&-17|2|h));for(a=v+1;a<u;a++)k(f,a,H(K(l(f,a))&-17|3|h));k(f,u,H(K(l(f,u))&-17|1|h))}else{k(f,v,H(K(l(f,v))&-49|
10|a|h));for(c=f+1;c<p;c++)k(c,v,H(K(l(c,v))&-33|12|a));k(p,v,H(K(l(p,v))&-49|6|a|h));for(c=v+1;c<u;c++)k(f,c,H(K(l(f,c))&-17|3|h)),k(p,c,H(K(l(p,c))&-17|3|h));k(f,u,H(K(l(f,u))&-49|9|a|h));for(c=f+1;c<p;c++)k(c,u,H(K(l(c,u))&-33|12|a));k(p,u,H(K(l(p,u))&-49|5|h|a))}}function*Q(a,c,g,e){let l=Math.abs(g-a),k=Math.abs(e-c),h=a<g?1:-1,f=c<e?1:-1,p=l-k;for(;;){yield[a,c];if(a===g&&c===e)break;let v=2*p;v>-k&&(p-=k,a+=h);v<l&&(p+=l,c+=f)}}function*T(a,c,g,e){let l=Math.sign(g-a),k=Math.sign(e-c);if(0===
l)if(0===k)yield[a,c];else for(g=c;g!==e+k;g+=k)yield[a,g];else if(0===k)for(;a!==g+l;a+=l)yield[a,c];else for(;c!==e+k;c+=k)for(let h=a;h!==g+l;h+=l)yield[h,c]}function*U(a,c,g,e){let l=Math.sign(g-a),k=Math.sign(e-c);if(0===l)if(0===k)yield[a,c];else for(g=c;g!==e+k;g+=k)yield[a,g];else if(0===k)for(e=a;e!==g+l;e+=l)yield[e,c];else{for(let h=a;h!==g+l;h+=l)yield[h,c];for(c+=k;c!==e;c+=k)yield[a,c],yield[g,c];for(;a!==g+l;a+=l)yield[a,e]}}function Z(){return new Promise((a,c)=>{let g=document.createElement("input");
g.type="file";g.onchange=e=>{var l;(null===(l=g.files)||void 0===l?0:l.length)?a(g.files[0]):a(null)};g.click()})}function G(a,c){let g=0;for(;a&c;){var e=Math.clz32(c);e=32-Math.clz32(~c<<e>>>e);e=c>>>e<<e;e&a&&(g|=e,a&=~e);c&=~e}return g}function aa(a,c,g,e,l,k,h){if(!(0>a||0>c||80<=a||25<=c)){var f=Math.floor(a%1*8),p=Math.floor(c%1*8);a=Math.floor(a);c=Math.floor(c);var {charCode:v,bgColor:u,fgColor:O}=g(a,c);if(u===O||32===v||255===v)v=0;var J=!!(l[v][p]&128>>>f),D=J?O:u,F=[],L=J?0:255,z=J?0:
65535,N=G(128>>>f,l[v][p]^L),E=G(32768>>>p,k[v][f]^z);a:if(0!==c){var P=N;for(let x=p-1;0<=x;x--)if(P=G(P,l[v][x]^L),0===P)break a;F.push({x:a,y:c-1,side:"bottom",mask:P})}a:if(24!==c){for(p+=1;8>p;p++)if(N=G(N,l[v][p]^L),0===N)break a;F.push({x:a,y:c+1,side:"top",mask:N})}a:if(0!==a){L=E;for(p=f-1;0<=p;p--)if(L=G(L,k[v][p]^z),0===L)break a;F.push({x:a-1,y:c,side:"right",mask:L})}a:if(79!==a){for(f+=1;8>f;f++)if(E=G(E,k[v][f]^z),0===E)break a;F.push({x:a+1,y:c,side:"left",mask:E})}J?e(a,c,v,h,u):
e(a,c,v,O,h);for(a=new Set([`${a},${c}`]);0<F.length;){let {x,y:b,side:d,mask:m}=F.pop(),{charCode:n,bgColor:r,fgColor:w}=g(x,b);if(r!==D&&w!==D||177===n||176===n&&r!==D||178===n&&w!==D)a.add(`${x},${b}`);else{if(w===r||32===n||255===n)n=0;c=r===D?255:0;J=r===D?65535:0;switch(d){case "top":for(z=E=f=0;16>z;z++){m=G(m,l[n][z]^c);if(0===m)break;m&128&&(f|=G(1<<z,k[n][0]^J));m&1&&(E|=G(1<<z,k[n][7]^J))}0<z&&(m&&24!==b&&!a.has(`${x},${b+1}`)&&F.push({x,y:b+1,side:"top",mask:m}),f&&0!==x&&!a.has(`${x-
1},${b}`)&&F.push({x:x-1,y:b,side:"right",mask:f}),E&&79!==x&&!a.has(`${x+1},${b}`)&&F.push({x:x+1,y:b,side:"left",mask:E}),r===D?e(x,b,n,w,h):e(x,b,n,h,r),a.add(`${x},${b}`));break;case "bottom":E=f=0;for(z=15;0<=z;z--){m=G(m,l[n][z]^c);if(0===m)break;m&128&&(f|=G(1<<z,k[n][0]^J));m&1&&(E|=G(1<<z,k[n][7]^J))}15>z&&(m&&0!==b&&!a.has(`${x},${b-1}`)&&F.push({x,y:b-1,side:"bottom",mask:m}),f&&0!==x&&!a.has(`${x-1},${b}`)&&F.push({x:x-1,y:b,side:"right",mask:f}),E&&79!==x&&!a.has(`${x+1},${b}`)&&F.push({x:x+
1,y:b,side:"left",mask:E}),r===D?e(x,b,n,w,h):e(x,b,n,h,r),a.add(`${x},${b}`));break;case "left":for(z=E=f=0;8>z;z++){m=G(m,k[n][z]^J);if(0===m)break;m&32768&&(E|=G(128>>z,l[n][15]^c));m&1&&(f|=G(128>>z,l[n][0]^c))}0<z&&(m&&79!==x&&!a.has(`${x+1},${b}`)&&F.push({x:x+1,y:b,side:"left",mask:m}),f&&0!==b&&!a.has(`${x},${b-1}`)&&F.push({x,y:b-1,side:"bottom",mask:f}),E&&24!==b&&!a.has(`${x},${b+1}`)&&F.push({x,y:b+1,side:"top",mask:E}),r===D?e(x,b,n,w,h):e(x,b,n,h,r),a.add(`${x},${b}`));break;case "right":E=
f=0;for(z=7;0<=z;z--){m=G(m,k[n][z]^J);if(0===m)break;m&32768&&(E|=G(128>>z,l[n][15]^c));m&1&&(f|=G(128>>z,l[n][0]^c))}7>z&&(m&&0!==x&&!a.has(`${x-1},${b}`)&&F.push({x:x-1,y:b,side:"right",mask:m}),f&&0!==b&&!a.has(`${x},${b-1}`)&&F.push({x,y:b-1,side:"bottom",mask:f}),E&&24!==b&&!a.has(`${x},${b+1}`)&&F.push({x,y:b+1,side:"top",mask:E}),r===D?e(x,b,n,w,h):e(x,b,n,h,r),a.add(`${x},${b}`))}}}}}let V=1===(new Uint8Array((new Uint16Array([1])).buffer))[0];var I;(function(a){a[a.Tile=255]="Tile";a[a.ForegroundColor=
3840]="ForegroundColor";a[a.BackgroundColor=61440]="BackgroundColor";a[a.All=65535]="All"})(I||(I={}));var W;(function(a){a[a.Black=0]="Black";a[a.DarkBlue=1]="DarkBlue";a[a.DarkGreen=2]="DarkGreen";a[a.DarkCyan=3]="DarkCyan";a[a.DarkRed=4]="DarkRed";a[a.DarkMagenta=5]="DarkMagenta";a[a.Brown=6]="Brown";a[a.LightGrey=7]="LightGrey";a[a.DarkGrey=8]="DarkGrey";a[a.Blue=9]="Blue";a[a.Green=10]="Green";a[a.Cyan=11]="Cyan";a[a.Red=12]="Red";a[a.Magenta=13]="Magenta";a[a.Yellow=14]="Yellow";a[a.White=15]=
"White"})(W||(W={}));let X="#000 #008 #080 #088 #800 #808 #880 #ccc #888 #00f #0f0 #0ff #f00 #f0f #ff0 #fff".split(" ");class ba{constructor(a){this.drawChar=a;this.buffer=new Uint16Array(2E3);this.buffer.fill(1792);this.canvas=document.createElement("canvas");this.canvas.width=640;this.canvas.height=400;this.ctx=this.canvas.getContext("2d");if(!this.ctx)throw Error("unable to get canvas context");}getBrush(a,c,g,e){if(!Number.isInteger(a)||!Number.isInteger(c))throw new TypeError("x and y must be integers");
if(!Number.isInteger(g)||!Number.isInteger(c))throw new TypeError("width and height must be integers");if(0>a||0>c||0>g||0>e||80<a+g||25<c+e)throw new RangeError("edges exceed screen");let l=new Uint16Array(g*e);for(let k=0;k<e;k++)l.set(this.buffer.subarray(80*(c+k)+a,80*(c+k)+a+g),k*g);return{data:l,width:g,height:e}}putBrush(a,c,g){let e,l,k=a.data;if(0>c){e=-c;if(e>=a.width)return;c=0}else e=0;l=Math.min(80-c,c+a.width);if(0>g){k=k.subarray(g*a.width);if(0===k.length)return;g=0}for(let h=0;h<
a.height;h++)if(!(0>g+h)){if(25<=g+h)break;this.buffer.set(k.subarray((g+h)*a.width+e,(g+h)*a.width+l),80*g+c);for(let f=e;f<l;f++)this.updateCanvas(g+h,c+f)}}updateCanvas(a,c){let g=this.buffer[80*c+a];this.drawChar(this.ctx,a,c,g&255,g>>8&15,g>>12&15)}getCharInfo(a,c){a=this.buffer[80*c+a];return{charCode:a&255,fgColor:a>>8&15,bgColor:a>>12&15}}getChar(a,c){return this.buffer[80*c+a]&255}putChar(a,c,g,e,l){this.buffer[80*c+a]=g|e<<8|l<<12;this.updateCanvas(a,c)}setChar(a,c,g,e,l,k=I.All){this.buffer[80*
c+a]=this.buffer[80*c+a]&~k|(g|e<<8|l<<12)&k;this.updateCanvas(a,c)}fill(a,c,g,e=I.All){a=(a|c<<8|g<<12)&e;for(c=0;c<this.buffer.length;c++)this.buffer[c]=this.buffer[c]&~e|a,this.updateCanvas(c%80,Math.floor(c/80))}putVHalf(a,c,g){var e=this.buffer[80*(c>>1)+a];let l=e>>>8&15,k=e>>>12&15,h=c&1;switch(e&255){case 219:case 8:case 10:e=l;break;default:e=k;break;case 220:e=1===h?k:l;break;case 223:e=1===h?l:k}e===g?this.putChar(a,c>>1,219,g,k):0===h?this.putChar(a,c>>1,223,g,e):this.putChar(a,c>>1,220,
g,e)}putHHalf(a,c,g){var e=this.buffer[80*c+(a>>1)];let l=e>>>8&15,k=e>>>12&15,h=a&1;switch(e&255){case 219:case 8:case 10:e=l;break;default:e=k;break;case 222:e=1===h?k:l;break;case 221:e=1===h?l:k}e===g?this.putChar(a>>1,c,219,g,k):0===h?this.putChar(a>>1,c,221,g,e):this.putChar(a>>1,c,222,g,e)}saveBlob(){if(V)return new Blob([this.buffer]);let a=new Uint16Array(this.buffer);for(let c=0;c<a.length;c++)a[c]=a[c]>>8|a[c]<<8;return new Blob([a],{type:"application/octet-stream"})}async loadBlob(a){a=
await a.arrayBuffer();if(a.byteLength!==this.buffer.byteLength)throw Error("invalid file");a=new Uint16Array(a);if(!V)for(var c=0;c<a.length;c++)a[c]=a[c]>>8|a[c]<<8;this.buffer.set(a);for(a=0;25>a;a++)for(c=0;80>c;c++)this.updateCanvas(c,a)}}let Y=new Uint8Array([0,193,194,179,180,217,191,180,195,192,218,195,196,193,194,197,0,208,210,186,180,189,183,182,195,211,214,199,196,208,210,215,0,180,203,179,181,190,184,181,198,212,213,198,205,207,209,216,0,208,210,186,181,188,187,185,198,200,201,204,205,
202,203,206]),S=new Uint8Array([3,7,39,23,22,38,55,19,54,53,21,37,6,9,13,14,11,12,15,43,27,57,58,61,62,59,44,63,45,29,46,30,25,41,42,26,31,47,5,10]),ca=fetch("./chardata.png"),da=a=>{var c=document.createElement("canvas");c.width=a.width;c.height=a.height;c=c.getContext("2d");if(!c)throw Error("unable to create 2D canvas");c.drawImage(a,0,0);var g=a.width/9;a=new Uint8Array(4096);for(let e=0;256>e;e++){const {data:l}=c.getImageData(e%g*9,16*Math.floor(e/g),8,16);for(let k=0;16>k;k++)a[16*e+k]=l[32*
k+3]?128:0,a[16*e+k]|=l[4*(8*k+1)+3]?64:0,a[16*e+k]|=l[4*(8*k+2)+3]?32:0,a[16*e+k]|=l[4*(8*k+3)+3]?16:0,a[16*e+k]|=l[4*(8*k+4)+3]?8:0,a[16*e+k]|=l[4*(8*k+5)+3]?4:0,a[16*e+k]|=l[4*(8*k+5)+3]?2:0,a[16*e+k]|=l[4*(8*k+7)+3]?1:0}c=Array(256);for(g=0;256>g;g++)c[g]=a.subarray(16*g,16*(g+1));return c},ea=a=>{const c=new Uint16Array(2048);for(var g=0;256>g;g++)for(let e=0;8>e;e++)for(let l=0;16>l;l++)c[8*g+e]|=(a[g][l]>>>7-e&1)<<l;a=Array(256);for(g=0;256>g;g++)a[g]=c.subarray(8*g,8*(g+1));return a};window.addEventListener("DOMContentLoaded",
async function(){var a=await (await ca).blob();let c=await createImageBitmap(a),g=c.width/9,e=(b,d,m,n,r,w)=>{b.save();b.globalCompositeOperation="source-over";b.fillStyle=X[w];b.fillRect(8*d,16*m,8,16);b.globalCompositeOperation="destination-out";b.drawImage(c,n%g*9,16*Math.floor(n/g),8,16,8*d,16*m,8,16);b.globalCompositeOperation="destination-over";b.fillStyle=X[r];b.fillRect(8*d,16*m,8,16);b.restore()},l=da(c),k=ea(l),h=new ba(e),f=document.getElementById("editor"),p=f.getContext("2d");if(!p)throw Error("unable to create canvas context");
let v=I.All;document.getElementById("tile").onchange=b=>{v=b.target.checked?v|I.Tile:v&~I.Tile};document.getElementById("fgcolor").onchange=b=>{v=b.target.checked?v|I.ForegroundColor:v&~I.ForegroundColor};document.getElementById("bgcolor").onchange=b=>{v=b.target.checked?v|I.BackgroundColor:v&~I.BackgroundColor};let u=[7,0,0],O=document.querySelector(".palette"),J=(b,d)=>{const m=d?"background-selected":"foreground-selected";var n=O.querySelectorAll(`.${m}`);for(let r=0;r<n.length;r++)n[r].classList.remove(m);
(n=O.querySelector(`.color-cell[data-value='${b}']`))&&n.classList.add(m);u[d?2:0]=b};O.onpointerdown=b=>{if("mouse"===b.pointerType&&(0===b.button||2===b.button)){var d=0===b.button?"foreground-selected":"background-selected";for(let m=b.target;m&&!m.classList.contains("palette");m=m.parentElement)if("value"in m.dataset){let n=O.querySelectorAll(`.${d}`);for(let r=0;r<n.length;r++)n[r].classList.remove(d);m.classList.add(d);u[b.button]=+m.dataset.value;b.preventDefault();b.stopPropagation();break}}};
O.oncontextmenu=b=>{b.preventDefault()};let D=[219,0,0],F={freehand:()=>{f.onpointerdown=b=>{if("mouse"===b.pointerType){const {button:w,pointerId:A}=b;if(0===w||2===w){function C(t){t.pointerId===A&&t.button===w&&(f.removeEventListener("pointermove",q),f.removeEventListener("pointerup",C))}function q(t){if(t.pointerId===A){var y=Math.floor(80*(t.clientX-d.x)/d.width);t=Math.floor(25*(t.clientY-d.y)/d.height);for(const [B,M]of Q(n,r,y,t))h.setChar(B,M,D[w],u[0],u[2],v);p.drawImage(h.canvas,0,0);n=
y;r=t}}b.preventDefault();f.setPointerCapture(A);var d=f.getBoundingClientRect(),m=Math.floor(80*(b.clientX-d.x)/d.width);b=Math.floor(25*(b.clientY-d.y)/d.height);h.setChar(m,b,D[w],u[0],u[2],v);p.drawImage(h.canvas,0,0);var n=m,r=b;f.addEventListener("pointermove",q);f.addEventListener("pointerup",C)}}}},vbFreehand:()=>{f.onpointerdown=b=>{if("mouse"===b.pointerType){const {button:w,pointerId:A}=b;if(0===w||2===w){function C(t){t.pointerId===A&&t.button===w&&(f.removeEventListener("pointermove",
q),f.removeEventListener("pointerup",C))}function q(t){if(t.pointerId===A){var y=Math.floor(80*(t.clientX-d.x)/d.width);t=Math.floor(50*(t.clientY-d.y)/d.height);for(const [B,M]of Q(n,r,y,t))h.putVHalf(B,M,u[w]);p.drawImage(h.canvas,0,0);n=y;r=t}}b.preventDefault();f.setPointerCapture(A);var d=f.getBoundingClientRect(),m=Math.floor(80*(b.clientX-d.x)/d.width);b=Math.floor(50*(b.clientY-d.y)/d.height);h.putVHalf(m,b,u[w]);p.drawImage(h.canvas,0,0);var n=m,r=b;f.addEventListener("pointermove",q);f.addEventListener("pointerup",
C)}}}},hbFreehand:()=>{f.onpointerdown=b=>{if("mouse"===b.pointerType){const {button:w,pointerId:A}=b;if(0===w||2===w){function C(t){t.pointerId===A&&t.button===w&&(f.removeEventListener("pointermove",q),f.removeEventListener("pointerup",C))}function q(t){if(t.pointerId===A){var y=Math.floor(160*(t.clientX-d.x)/d.width);t=Math.floor(25*(t.clientY-d.y)/d.height);for(const [B,M]of Q(n,r,y,t))h.putHHalf(B,M,u[w]);p.drawImage(h.canvas,0,0);n=y;r=t}}b.preventDefault();f.setPointerCapture(A);var d=f.getBoundingClientRect(),
m=Math.floor(160*(b.clientX-d.x)/d.width);b=Math.floor(25*(b.clientY-d.y)/d.height);h.putHHalf(m,b,u[w]);p.drawImage(h.canvas,0,0);var n=m,r=b;f.addEventListener("pointermove",q);f.addEventListener("pointerup",C)}}}},lines:()=>{f.onpointerdown=b=>{if("mouse"===b.pointerType){const {button:r,pointerId:w}=b;if(0===r||2===r){function A(q){if(q.pointerId===w&&q.button===r){var t=Math.floor(80*(q.clientX-d.x)/d.width);q=Math.floor(25*(q.clientY-d.y)/d.height);for(const [y,B]of Q(m,n,t,q))h.setChar(y,B,
D[r],u[0],u[2],v);p.globalCompositeOperation="copy";p.drawImage(h.canvas,0,0);f.removeEventListener("pointermove",C);f.removeEventListener("pointerup",A)}}function C(q){if(q.pointerId===w){var t=Math.floor(80*(q.clientX-d.x)/d.width);q=Math.floor(25*(q.clientY-d.y)/d.height);p.globalCompositeOperation="copy";p.drawImage(h.canvas,0,0);for(const [y,B]of Q(m,n,t,q))e(p,y,B,D[r],u[0],u[2])}}b.preventDefault();f.setPointerCapture(w);var d=f.getBoundingClientRect(),m=Math.floor(80*(b.clientX-d.x)/d.width),
n=Math.floor(25*(b.clientY-d.y)/d.height);e(p,m,n,D[r],u[0],u[2]);f.addEventListener("pointermove",C);f.addEventListener("pointerup",A)}}}},filledBox:()=>{f.onpointerdown=b=>{if("mouse"===b.pointerType){const {button:r,pointerId:w}=b;if(0===r||2===r){function A(q){if(q.pointerId===w&&q.button===r){var t=Math.floor(80*(q.clientX-d.x)/d.width);q=Math.floor(25*(q.clientY-d.y)/d.height);for(const [y,B]of T(m,n,t,q))h.setChar(y,B,D[r],u[0],u[2],v);p.globalCompositeOperation="copy";p.drawImage(h.canvas,
0,0);f.removeEventListener("pointermove",C);f.removeEventListener("pointerup",A)}}function C(q){if(q.pointerId===w){var t=Math.floor(80*(q.clientX-d.x)/d.width);q=Math.floor(25*(q.clientY-d.y)/d.height);p.globalCompositeOperation="copy";p.drawImage(h.canvas,0,0);for(const [y,B]of T(m,n,t,q))e(p,y,B,D[r],u[0],u[2])}}b.preventDefault();f.setPointerCapture(w);var d=f.getBoundingClientRect(),m=Math.floor(80*(b.clientX-d.x)/d.width),n=Math.floor(25*(b.clientY-d.y)/d.height);e(p,m,n,D[r],u[0],u[2]);f.addEventListener("pointermove",
C);f.addEventListener("pointerup",A)}}}},emptyBox:()=>{f.onpointerdown=b=>{if("mouse"===b.pointerType){const {button:r,pointerId:w}=b;if(0===r||2===r){function A(q){if(q.pointerId===w&&q.button===r){var t=Math.floor(80*(q.clientX-d.x)/d.width);q=Math.floor(25*(q.clientY-d.y)/d.height);for(const [y,B]of U(m,n,t,q))h.setChar(y,B,D[r],u[0],u[2],v);p.globalCompositeOperation="copy";p.drawImage(h.canvas,0,0);f.removeEventListener("pointermove",C);f.removeEventListener("pointerup",A)}}function C(q){if(q.pointerId===
w){var t=Math.floor(80*(q.clientX-d.x)/d.width);q=Math.floor(25*(q.clientY-d.y)/d.height);p.globalCompositeOperation="copy";p.drawImage(h.canvas,0,0);for(const [y,B]of U(m,n,t,q))e(p,y,B,D[r],u[0],u[2])}}b.preventDefault();f.setPointerCapture(w);var d=f.getBoundingClientRect(),m=Math.floor(80*(b.clientX-d.x)/d.width),n=Math.floor(25*(b.clientY-d.y)/d.height);e(p,m,n,D[r],u[0],u[2]);f.addEventListener("pointermove",C);f.addEventListener("pointerup",A)}}}},singleBorder:()=>{f.onpointerdown=b=>{if("mouse"===
b.pointerType){const {button:r,pointerId:w}=b;if(0===r||2===r){function A(q){q.pointerId===w&&q.button===r&&(R(m,n,Math.floor(80*(q.clientX-d.x)/d.width),Math.floor(25*(q.clientY-d.y)/d.height),(t,y)=>h.getChar(t,y),(t,y,B)=>h.putChar(t,y,B,u[0],u[2]),!1),p.globalCompositeOperation="copy",p.drawImage(h.canvas,0,0),f.removeEventListener("pointermove",C),f.removeEventListener("pointerup",A))}function C(q){if(q.pointerId===w){var t=Math.floor(80*(q.clientX-d.x)/d.width);q=Math.floor(25*(q.clientY-d.y)/
d.height);p.globalCompositeOperation="copy";p.drawImage(h.canvas,0,0);R(m,n,t,q,(y,B)=>h.getChar(y,B),(y,B,M)=>e(p,y,B,M,u[0],u[2]),!1)}}b.preventDefault();f.setPointerCapture(w);var d=f.getBoundingClientRect(),m=Math.floor(80*(b.clientX-d.x)/d.width),n=Math.floor(25*(b.clientY-d.y)/d.height);e(p,m,n,H(15),u[0],u[2]);f.addEventListener("pointermove",C);f.addEventListener("pointerup",A)}}}},doubleBorder:()=>{f.onpointerdown=b=>{if("mouse"===b.pointerType){const {button:r,pointerId:w}=b;if(0===r||2===
r){function A(q){q.pointerId===w&&q.button===r&&(R(m,n,Math.floor(80*(q.clientX-d.x)/d.width),Math.floor(25*(q.clientY-d.y)/d.height),(t,y)=>h.getChar(t,y),(t,y,B)=>h.putChar(t,y,B,u[0],u[2]),!0),p.globalCompositeOperation="copy",p.drawImage(h.canvas,0,0),f.removeEventListener("pointermove",C),f.removeEventListener("pointerup",A))}function C(q){if(q.pointerId===w){var t=Math.floor(80*(q.clientX-d.x)/d.width);q=Math.floor(25*(q.clientY-d.y)/d.height);p.globalCompositeOperation="copy";p.drawImage(h.canvas,
0,0);R(m,n,t,q,(y,B)=>h.getChar(y,B),(y,B,M)=>e(p,y,B,M,u[0],u[2]),!0)}}b.preventDefault();f.setPointerCapture(w);var d=f.getBoundingClientRect(),m=Math.floor(80*(b.clientX-d.x)/d.width),n=Math.floor(25*(b.clientY-d.y)/d.height);e(p,m,n,H(15),u[0],u[2]);f.addEventListener("pointermove",C);f.addEventListener("pointerup",A)}}}},colorFloodFill:()=>{f.onpointerdown=b=>{if("mouse"===b.pointerType){const {button:m}=b;if(0===m||2===m){b.preventDefault();var d=f.getBoundingClientRect();aa(80*(b.clientX-d.x)/
d.width,25*(b.clientY-d.y)/d.height,(n,r)=>h.getCharInfo(n,r),(n,r,w,A,C)=>h.putChar(n,r,w,A,C),l,k,u[m]);p.globalCompositeOperation="copy";p.drawImage(h.canvas,0,0)}}}},pick:()=>{f.onpointerdown=b=>{if("mouse"===b.pointerType){const {button:w,pointerId:A}=b;if(0===w||2===w){function C(t){t.pointerId===A&&t.button===w&&(f.removeEventListener("pointermove",q),f.removeEventListener("pointerup",C))}function q(t){if(t.pointerId===A&&t.button===w){var y=f.getBoundingClientRect(),{charCode:B,fgColor:M,
bgColor:fa}=h.getCharInfo(Math.floor(80*(t.clientX-y.x)/y.width),Math.floor(25*(t.clientY-y.y)/y.height));v&I.Tile&&x(B,2===w);v&I.ForegroundColor&&J(M,!1);v&I.BackgroundColor&&J(fa,!0)}}b.preventDefault();f.setPointerCapture(A);var d=f.getBoundingClientRect(),{charCode:m,fgColor:n,bgColor:r}=h.getCharInfo(Math.floor(80*(b.clientX-d.x)/d.width),Math.floor(25*(b.clientY-d.y)/d.height));v&I.Tile&&x(m,2===w);v&I.ForegroundColor&&J(n,!1);v&I.BackgroundColor&&J(r,!0);f.addEventListener("pointermove",q);
f.addEventListener("pointerup",C)}}}}};F.freehand();let L=document.getElementById("tool-selector"),z=L.value;document.body.classList.add("tool-"+z);L.onchange=b=>{F[L.value]();document.body.classList.remove("tool-"+z);z=L.value;document.body.classList.add("tool-"+z)};f.oncontextmenu=b=>{b.preventDefault()};let N=document.getElementById("char-picker"),E=document.querySelector(".left-pick"),P=document.querySelector(".right-pick"),x=(b,d)=>{const m=Math.floor(b/64),n=d?P:E;n.style.left=`${b%64*8}px`;
n.style.top=`${16*m}px`;D[d?2:0]=b};a=N.getContext("2d");if(!a)throw Error("unable to create canvas context");for(let b=0;256>b;b++)e(a,b%64,Math.floor(b/64),b,7,0);N.onpointerdown=b=>{if("mouse"===b.pointerType&&(0===b.button||2===b.button)){var d=N.getBoundingClientRect();x(64*Math.floor(4*(b.clientY-d.y)/d.height)+Math.floor(64*(b.clientX-d.x)/d.width),2===b.button)}};N.oncontextmenu=b=>{b.preventDefault()};document.getElementById("save-image").onclick=b=>{b=h.saveBlob();b=URL.createObjectURL(b);
let d=document.createElement("a");d.download="dosimage.dat";d.href=b;d.click()};document.getElementById("load-image").onclick=async b=>{if(b=await Z()){try{await h.loadBlob(b)}catch(d){alert(d);return}p.drawImage(h.canvas,0,0)}};document.getElementById("clear-image").onclick=b=>{h.fill(D[2],u[0],u[2],v);p.drawImage(h.canvas,0,0)}},{once:!0})})()
